# ============================================================================
# cmake配置
# ============================================================================
cmake:
  use_gpu: true #开启则自动编译并使用gpu
